name: pre_sqlite
description: "Prueba para archivo sqlite"
 
# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.

publish_to: 'none'  # Elimine esta línea si desea publicar en pub.dev
#
#
# A continuación se definen la versión y el número de compilación de su aplicación.
#Un número de versión son tres números separados por puntos, como 1.2.43
#seguido de un número de compilación opcional separado por un +.
#Tanto la versión como el número de compilación se pueden anular en flutter
#build especificando --build-name y --build-number, respectivamente.
#En Android, build-name se utiliza como versionName mientras que build-number se utiliza como version
#Más información sobre el versionado de Android en https://developer.android.com/studio/publi
#En iOS, build-name se utiliza como CFBundleShortVersionString mientras que build-number es u
#Más información sobre el control de versiones de iOS en
#https://developer.apple.com/library/archive/documentation/General/Reference/Info
#En Windows, build-name se utiliza como las partes major, minor y patch
#de las versiones de productos y archivos, mientras que build-number se utiliza como sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

 
# Las dependencias especifican otros paquetes que su paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de su paquete a las últimas versiones
# considere ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias pueden ser actualizadas manualmente cambiando los números de versión de abajo a
# la última versión disponible en pub.dev. Para ver qué dependencias tienen versiones
# versiones más recientes, ejecute `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter


  
 # Lo siguiente añade la fuente Cupertino Icons a tu aplicación.
  # Usar con la clase CupertinoIcons para iconos estilo iOS.

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# El paquete «flutter_lints» contiene un conjunto de lints recomendados para
  # fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete se
  # activado en el archivo `analysis_options.yaml` ubicado en la raíz de su
  # paquete. Consulte ese archivo para obtener información sobre la desactivación de reglas # específicas de lint y la activación de otras adicionales.
  # y activar otras adicionales.

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/employee.db
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
